### ISSUE TITLE
Crash on update check

### ISSUE THREAD

**Issue by probablypablito** [chenxiaolong/Custota#39]
I'm on GrapheneOS 14 and connecting over HTTP via a VPN to my update server. 

There seems to be some permission denied error.

[Custota log 6faa805cb0a6.txt](https://github.com/chenxiaolong/Custota/files/14474336/Custota.log.6faa805cb0a6.txt)

**Comment by chenxiaolong** [comment]
That's really strange. It's failing to create a file to save its logs. I'm not sure what would prevent Custota from writing to its own directory. I know GrapheneOS has some storage restrictions, like the storage scopes feature, but that shouldn't apply here.

To try and troubleshoot this, can you post the outputs of these commands?

```
adb shell su -c 'ls -lZd /data/media/0/Android/data/com.chiller3.custota/files /data/data/com.chiller3.custota'
adb shell pm dump com.chiller3.custota | grep 'uid=.*gids='
```

I just want to make sure this isn't just some filesystem permissions issue.

On my device, it looks like this:

```
drwx------ 6 u0_a281 u0_a281     u:object_r:app_data_file:s0:c25,c257,c512,c768       3452 2023-12-12 09:05 /data/data/com.chiller3.custota
                 ^^^     ^^^                              *********************
drwxrws--- 2 u0_a281 ext_data_rw u:object_r:media_rw_data_file:s0:c25,c257,c512,c768  3452 2023-12-30 10:51 /data/media/0/Android/data/com.chiller3.custota/files
                 ^^^                                           *********************
    uid=10281 gids=[] type=0 prot=signature
          ^^^
```

The highlighted parts (user ID `^^^` and SELinux MCS `***`) should match.

**Comment by probablypablito** [comment]
```cmd
PS C:\Users\Pablo> adb shell su -c 'ls -lZd /data/media/0/Android/data/com.chiller3.custota/files /data/data/com.chiller3.custota'
drwx------ 6 u0_a77 u0_a77      u:object_r:app_data_file:s0:c77,c256,c512,c768  3452 2024-03-03 14:41 /data/data/com.chiller3.custota
drwxrws--- 2 u0_a77 ext_data_rw u:object_r:media_rw_data_file:s0                3452 2024-02-18 16:49 /data/media/0/Android/data/com.chiller3.custota/files
```

```cmd
PS C:\Users\Pablo> adb shell pm dump com.chiller3.custota | findstr.exe 'uid=.*gids='
    uid=10077 gids=[] type=0 prot=signature
    
```

**Comment by chenxiaolong** [comment]
Thanks. That `u:object_r:media_rw_data_file:s0` definitely looks wrong. I would suggest deleting the entire `/data/media/0/Android/data/com.chiller3.custota` directory, rebooting, and seeing if that fixes the problem.

(I'm not sure how it ended up in that state though. That app directory is created by Android before the app launches the first time.)

**Comment by josevega96** [comment]
I'm getting a crash also in pixel stock with the march security patch , I could update from the February patch to the march patch without any issue , but after the update I began getting the error 
![Screenshot_20240304-173704](https://github.com/chenxiaolong/Custota/assets/34356719/714c02dc-0dc6-464c-bde8-470908506cfc)

**Comment by chenxiaolong** [comment]
@josevega96 Thanks. I've opened a new issue over at #40 for this as it's unrelated to this specific issue.

**Comment by probablypablito** [comment]
I followed the deletion instructions but now receive this error:

```txt
Failed to install OTA update

IOException (Failed to download update info)
-> SocketException (Binding socket to network
108 failed: EPERM (Operation not permitted)) ->
ErrnoException (Binding socket to network 108
failed: EPERM (Operation not permitted))
```

I've tried re-deleting the directory but to no avail.

**Comment by chenxiaolong** [comment]
If I remember correctly, GrapheneOS has a permission toggle for each app for network access. Can you double check that it is enabled?

**Comment by probablypablito** [comment]
It is enabled. Do you need more logs or a screen recording? I'm unsure what could've caused this as I had Custota working before I updated to v3 / avbroot v3

**Comment by probablypablito** [comment]
```cmd
C:\Users\Pablo>adb shell "ps -efZ | grep custota"
u:r:custota_app:s0:c77,c256,c512,c768 u0_a77 21180  922 11 13:37:26 ?    00:00:00 com.chiller3.custota
u:r:shell:s0                   shell        21220  1249 2 13:37:29 ?     00:00:00 sh -c ps -efZ | grep custota
u:r:shell:s0                   shell        21223 21220 7 13:37:29 ?     00:00:00 grep custota
```

No new output was printed for the second command.

**Comment by chenxiaolong** [comment]
Thanks. So everything SELinux-related is good. I really have no idea what else would cause the `ErrnoException (Binding socket to network 108 failed: EPERM (Operation not permitted))`.

The only thing left I could suggest is the brute force approach: maybe try uninstalling the Custota module completely and booting once without it installed (so that Android will delete all of Custota's data). It probably won't help, but I don't really have any more ideas for what the problem might be.

**Comment by probablypablito** [comment]
Tried to no avail :(

No idea what it is either, but this is definitely annoying. I'll miss using it! I'll open another issue / contact you if I find a solution.

**Comment by probablypablito** [comment]
Oh wow literally just now I found the issue: my WireGuard VPN running in root mode.

WireGuard on Android can be ran either in userspace or (with root) in kernel mode. The latter seems to make Custota unhappy. Turning off the VPN or setting it back to userspace seems to fix that specific issue.

**Comment by chenxiaolong** [comment]
Oh wow, nice find.

Custota (and also Android's underlying `update_engine`) use Android's special [`Network` API](https://developer.android.com/reference/android/net/Network) for all connections. It's the standard way to handle things like only connecting if the user is on an unmetered network. I know Android's implementation of this API does a bunch of things behind the scenes, like setting up `fwmark` firewall rules. At least on desktop Linux, WireGuard also sets up its own `fwmark` firewall rules. I wonder that's causing some sort of conflict. Userspace mode wouldn't be affected since that goes through Android's VPN APIs.

**Comment by nixigaj** [comment]
Was just about to report an issue here but yeah, I have the same issue with kernel mode WireGuard, even if `AllowedIPs` is only set to a private range that has nothing to do with my OTA server.

**Comment by chenxiaolong** [comment]
It might be possible to work around the problem by having Custota pre-download the OTA and then pass a local file to `update_engine`, but I'm not sure. That isn't something I plan to implement though.

**Comment by chenxiaolong** [comment]
Actually, I have one final idea. Please give this test build a try: [Custota-5.6.r4.g979cc73-release.zip](https://github.com/user-attachments/files/19273957/Custota-5.6.r4.g979cc73-release.zip)

You'll have to long press Custota's version number to enable the debug options and then turn off the `Pass network ID to update_engine` setting.

I have no idea if this will work. If it does, the main thing that will be impacted is the unmetered network setting. When `Pass network ID to update_engine` is turned off, the unmetered network setting will be respected by Custota, but not by `update_engine`, so it could potentially download the entire OTA over a metered network (eg. if Wi-Fi disconnects during the download).

**Comment by nixigaj** [comment]
It did not make a difference unfortunately, same socket exception as before, and works again when disabling the WireGuard interface. If you have time to try more debug builds just send them here and I will try them.

I'm running Android 15 via GrapheneOS 2020030200+ on a Pixel 9 Pro with a self signed custom build with Magisk added, if that is relevant.

**Comment by chenxiaolong** [comment]
Thanks for testing! Could you run `adb logcat -s update_engine`, retest one more time with `Pass network ID to update_engine` unchecked, and then post the new log output?

I just want to double check that it's failing for exactly the same reason.

**Comment by nixigaj** [comment]
When running `adb logcat -s update_engine` and pressing the `Check for updates` button I get no output at all. I ran just `adb logcat` for 1s while clicking the button and removed 20MB of logs around where I assume the update check event happens. This is the contents of that part:


<details><summary>Logs</summary><pre><code>03-17 04:26:13.679 24943 24943 D UpdaterJob: Scheduling job:  {requiredNetwork=NetworkRequest [ NONE id=0, [ Capabilities: INTERNET&TRUSTED&VALIDATED&NOT_VCN_MANAGED&NOT_BANDWIDTH_CONSTRAINED Uid: 10160 UnderlyingNetworks: Null] ], isRequiredBatteryNotLow=false, isPersisted=false, intervalMillis=0, extras=PersistableBundle[{action=1}]}
03-17 04:26:13.680  1602  3144 D CompatChangeReporter: Compat change id reported: 311402873; UID 10160; state: ENABLED
03-17 04:26:13.680  1602  3144 D CompatChangeReporter: Compat change id reported: 323349338; UID 10160; state: ENABLED
03-17 04:26:13.683 24943 24943 D UpdaterJob: Scheduled job:  {requiredNetwork=NetworkRequest [ NONE id=0, [ Capabilities: INTERNET&TRUSTED&VALIDATED&NOT_VCN_MANAGED&NOT_BANDWIDTH_CONSTRAINED Uid: 10160 UnderlyingNetworks: Null] ], isRequiredBatteryNotLow=false, isPersisted=false, intervalMillis=0, extras=PersistableBundle[{action=1}]}
03-17 04:26:13.698  1602  3144 D CompatChangeReporter: Compat change id reported: 311208749; UID 10160; state: ENABLED
03-17 04:26:13.698  1602  3144 I ActivityManager: Background started FGS: Allowed [callingPackage: com.chiller3.custota; callingUid: 10160; uidState: TOP ; uidBFSL: [BFSL]; intent: Intent { act=com.chiller3.custota.updater.UpdaterService.start cmp=com.chiller3.custota/.updater.UpdaterService (has extras) }; code:PROC_STATE_TOP; tempAllowListReason:<,reasonCode:SYSTEM_ALLOW_LISTED,duration:9223372036854775807,callingUid:-1>; targetSdkVersion:35; callerTargetSdkVersion:35; startForegroundCount:0; bindFromPackage:null: isBindService:false]
03-17 04:26:13.699  1602  3144 D CompatChangeReporter: Compat change id reported: 311208629; UID 10160; state: ENABLED
03-17 04:26:13.705 24943 24943 D UpdaterService: Received intent: Intent { act=com.chiller3.custota.updater.UpdaterService.start cmp=com.chiller3.custota/.updater.UpdaterService (has extras) }
03-17 04:26:13.705 24943 24943 D UpdaterService: Updating foreground notification for state: null
03-17 04:26:13.714  1602 14527 D CompatChangeReporter: Compat change id reported: 296558535; UID 10160; state: ENABLED
03-17 04:26:13.714  1602 14527 D CompatChangeReporter: Compat change id reported: 317799821; UID 10160; state: ENABLED
03-17 04:26:13.714  1602 14527 D CompatChangeReporter: Compat change id reported: 313677553; UID 10160; state: ENABLED
03-17 04:26:13.715  1602 14527 W ForegroundServiceTypeLoggerModule: Foreground service start for UID: 10160 does not have any types
03-17 04:26:13.717 24943 24943 D UpdaterService: Creating new updater thread
03-17 04:26:13.718 24943 24943 D UpdaterService: Updating foreground notification for state: null
03-17 04:26:13.747 24943 24963 D UpdaterThread: onStatusUpdate(0/IDLE, 0.0%)
03-17 04:26:13.747 24943 24943 D UpdaterService: More silent behavior for periodic job: false
03-17 04:26:13.747 24943 24943 D UpdaterService: Trying to stop service if possible
03-17 04:26:13.748 24943 24984 D UpdaterThread: Starting log file (5.6.r4.g979cc73)
03-17 04:26:13.765 24943 24984 D UpdaterThread: Action: CHECK
03-17 04:26:13.765 24943 24984 D UpdaterThread: Waiting for initial engine status
03-17 04:26:13.765 24943 24984 D UpdaterThread: Initial status: 0/IDLE
03-17 04:26:13.765 24943 24984 D UpdaterThread: Starting new update because engine is idle
03-17 04:26:13.766 24943 24984 D UpdaterThread: Update info URI: https://nixigaj.github.io/rooted-graphene/magisk/caiman.json
03-17 04:26:13.766 24943 24943 D UpdaterService: Updating foreground notification for state: ProgressState(type=CHECK, current=0, max=0)
03-17 04:26:13.766 24985 24985 W logcat  : type=1400 audit(0.0:14329): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=388 scontext=u:r:custota_app:s0:c160,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=com.chiller3.custota
03-17 04:26:13.771 24985 24985 W libc    : Access denied finding property "ro.debuggable"
03-17 04:26:13.801  1119  1153 E Netd    : uid 10160 can't select networks other than 31530.
03-17 04:26:13.838  2493  4112 D PowerUI : can't show warning due to - plugged: true status unknown: false
03-17 04:26:13.945  1602  1602 W NotificationHistory: Attempted to add notif for locked/gone/disabled user 0
03-17 04:26:14.015  2493  3005 D LocalImageResolver: Couldn't use ImageDecoder for drawable, falling back to non-resized load.
03-17 04:26:14.037  2493  3005 D LocalImageResolver: Couldn't use ImageDecoder for drawable, falling back to non-resized load.
03-17 04:26:14.048  2493  3005 D LocalImageResolver: Couldn't use ImageDecoder for drawable, falling back to non-resized load.
03-17 04:26:14.082 24943 24984 D TrafficStats: tagSocket(96) with statsTag=0xffffffff, statsUid=-1
03-17 04:26:14.083  1119  1155 E Netd    : uid 10160 can't select networks other than 31530.
03-17 04:26:14.084 24943 24984 D TrafficStats: tagSocket(96) with statsTag=0xffffffff, statsUid=-1
03-17 04:26:14.084  1119  1155 E Netd    : uid 10160 can't select networks other than 31530.
03-17 04:26:14.084 24943 24984 D TrafficStats: tagSocket(96) with statsTag=0xffffffff, statsUid=-1
03-17 04:26:14.084  1119  1155 E Netd    : uid 10160 can't select networks other than 31530.
03-17 04:26:14.085 24943 24984 D TrafficStats: tagSocket(97) with statsTag=0xffffffff, statsUid=-1
03-17 04:26:14.085  1119  1155 E Netd    : uid 10160 can't select networks other than 31530.
03-17 04:26:14.085 24943 24984 D UpdaterThread: Delete /data/ota_package/care_map.pb result: false
03-17 04:26:14.087 24943 24984 E UpdaterThread: Failed to install update
03-17 04:26:14.087 24943 24984 E UpdaterThread: java.io.IOException: Failed to download update info
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at com.chiller3.custota.updater.UpdaterThread.checkForUpdates(Unknown Source:2256)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at com.chiller3.custota.updater.UpdaterThread.run(Unknown Source:283)
03-17 04:26:14.087 24943 24984 E UpdaterThread: Caused by: java.net.SocketException: Binding socket to network 104 failed: EPERM (Operation not permitted)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at android.net.Network.bindSocket(Network.java:442)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at android.net.Network.bindSocket(Network.java:409)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at android.net.Network$NetworkBoundSocketFactory.createSocket(Network.java:269)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:114)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at com.chiller3.custota.updater.UpdaterThread.fetchUpdateInfo(Unknown Source:58)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at com.chiller3.custota.updater.UpdaterThread.checkForUpdates(Unknown Source:54)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	... 1 more
03-17 04:26:14.087 24943 24984 E UpdaterThread: Caused by: android.system.ErrnoException: Binding socket to network 104 failed: EPERM (Operation not permitted)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	at android.net.Network.bindSocket(Network.java:441)
03-17 04:26:14.087 24943 24984 E UpdaterThread: 	... 16 more
03-17 04:26:14.090 24943 24984 D UpdaterThread: Stopping log file
03-17 04:26:14.093 24943 24943 D UpdaterService: Trying to stop service if possible
03-17 04:26:14.093 24943 24943 D UpdaterService: Updater thread completed; stopping service
03-17 04:26:14.094  1602 14537 W ForegroundServiceTypeLoggerModule: FGS stop call for: 10160 has no types!
03-17 04:26:14.098  3218  5418 D androidtc: Initializing SystemTextClassifier, type = System
03-17 04:26:14.301  1602  1602 I AS.AudioService: shouldNotificationSoundPlay false: muted stream:5 attr:AudioAttributes: usage=USAGE_NOTIFICATION content=CONTENT_TYPE_SONIFICATION flags=0x800 tags= bundle=null
03-17 04:26:14.302  1602  1602 D FlashNotifController: requestStartFlashNotification
03-17 04:26:14.303  1602  1602 I FlashNotifController: startFlashNotification: type=1, tag=android
03-17 04:26:14.303  1602  1602 D FlashNotifController: Flash notification is disabled
03-17 04:26:14.310  1602  1602 W NotificationHistory: Attempted to add notif for locked/gone/disabled user 0
03-17 04:26:14.344  2493  3005 D LocalImageResolver: Couldn't use ImageDecoder for drawable, falling back to non-resized load.
03-17 04:26:14.363  2493  3005 D LocalImageResolver: Couldn't use ImageDecoder for drawable, falling back to non-resized load.
03-17 04:26:14.379  2493  3005 D LocalImageResolver: Couldn't use ImageDecoder for drawable, falling back to non-resized load.
03-17 04:26:14.392  2493  3005 D LocalImageResolver: Couldn't use ImageDecoder for drawable, falling back to non-resized load.
03-17 04:26:14.394  2493  2493 W TouchableRegionManager: onHeadsUpPinnedModeChanged
03-17 04:26:14.397  1602 14537 D CoreBackPreview: Window{6b5ea06 u0 NotificationShade}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@2556c0, mPriority=0, mIsAnimationCallback=false}
03-17 04:26:14.460  1602  1793 D SystemServerTiming: getUserSwitchability-0
03-17 04:26:14.460  1602  3144 D SystemServerTiming: getUserSwitchability-0
03-17 04:26:14.460  1602  1793 D SystemServerTiming: TM.isInCall
03-17 04:26:14.461  1602  3144 D SystemServerTiming: TM.isInCall
03-17 04:26:14.461  2493  2493 D BiometricsRepositoryImpl: currentUser authFlags changed, new value: AuthenticationFlags(userId=0, flag=0)
03-17 04:26:14.461  1602  1793 D SystemServerTiming: hasUserRestriction-DISALLOW_USER_SWITCH
03-17 04:26:14.461  1602  3144 D SystemServerTiming: hasUserRestriction-DISALLOW_USER_SWITCH
03-17 04:26:14.461  1602  1793 D SystemServerTiming: getInt-ALLOW_USER_SWITCHING_WHEN_SYSTEM_USER_LOCKED
03-17 04:26:14.461  1602  3144 D SystemServerTiming: getInt-ALLOW_USER_SWITCHING_WHEN_SYSTEM_USER_LOCKED
03-17 04:26:14.461  2493  2493 D BiometricsRepositoryImpl: currentUser authFlags changed, new value: AuthenticationFlags(userId=0, flag=0)
03-17 04:26:14.462  1602  1793 D SystemServerTiming: isUserUnlocked-USER_SYSTEM
03-17 04:26:14.462  1602  3144 D SystemServerTiming: isUserUnlocked-USER_SYSTEM
03-17 04:26:14.462  2493  2493 D BiometricsRepositoryImpl: currentUser authFlags changed, new value: AuthenticationFlags(userId=0, flag=0)
03-17 04:26:14.462  2493  2493 D BiometricsRepositoryImpl: currentUser authFlags changed, new value: AuthenticationFlags(userId=0, flag=0)
03-17 04:26:14.462  2493  2493 D BiometricsRepositoryImpl: currentUser authFlags changed, new value: AuthenticationFlags(userId=0, flag=0)
03-17 04:26:14.462  2493  2493 D BiometricsRepositoryImpl: currentUser authFlags changed, new value: AuthenticationFlags(userId=0, flag=0)
03-17 04:26:14.908  1753  1753 D Vibrator: Took 0 ms to wait for the actuator activation.
03-17 04:26:14.972  1753 24995 D Vibrator: waitForComplete: Vibrator is already off
03-17 04:26:15.188  1485  1485 D AOC     : A3:MSG: tmd3733_device.cc, 873: USF: TMD3733: Switch lux calc 0->2 d_lux:0.54 m_lux:0.00 R:0.25 C:0.24.
03-17 04:26:15.202  1485  1485 D AOC     : A3:MSG: tmd3733_device.cc, 873: USF: TMD3733: Switch lux calc 2->0 d_lux:4.18 m_lux:0.00 R:0.00 C:0.24.
03-17 04:26:15.231  1753 24996 D Vibrator: waitForComplete: Vibrator is already off
03-17 04:26:15.330  2172  2194 I pixel-thermal: usb_pwr_therm:35.846 raw data: usb_pwr_therm:35846 
03-17 04:26:15.336  2172  2194 I pixel-thermal: VIRTUAL-USB-THROTTLING:35.846 raw data: VIRTUAL-USB-THROTTLING:35846 usb_pwr_therm:35846 
03-17 04:26:15.336  2172  2194 I pixel-thermal: VIRTUAL-USB-UI:35.846 raw data: VIRTUAL-USB-UI:35846 usb_pwr_therm:35846 
03-17 04:26:15.413  1485  1485 D AOC     : A3:MSG: tmd3733_device.cc, 873: USF: TMD3733: Switch lux calc 0->2 d_lux:-.35 m_lux:0.00 R:0.25 C:0.24.
03-17 04:26:15.425  1485  1485 D AOC     : A3:MSG: tmd3733_device.cc, 873: USF: TMD3733: Switch lux calc 2->0 d_lux:5.22 m_lux:0.00 R:0.00 C:0.24.
03-17 04:26:15.801 24943 24997 D ProfileInstaller: Skipping profile installation for com.chiller3.custota</code></pre></details>

**Comment by chenxiaolong** [comment]
Oh, that's super interesting. So, the wireguard kernel mode isn't just breaking update_engine. It's also breaking Custota itself (`UpdaterThread` is Custota):
```
03-17 04:26:14.087 24943 24984 E UpdaterThread: Caused by: android.system.ErrnoException: Binding socket to network 104 failed: EPERM (Operation not permitted)
```

Given that, I suspect any app that sets requirements for a specific network type is broken. (It's Android's only reliable API for guaranteeing that traffic doesn't leak to a metered network, but not many apps use it.)

Please give this a try and disable the new `Pin to specific network ID` option: [Custota-5.6.r4.gdcf8001-release.zip](https://github.com/user-attachments/files/19279015/Custota-5.6.r4.gdcf8001-release.zip)

**Comment by nixigaj** [comment]
Yep, it works now with `Pin to specific network ID` disabled! It works using both partially and fully tunneled interfaces (`10.x.x.x/24, fdxx::/64` and `0.0.0.0/0, ::/0`). I did an actual GrapheneOS OTA update through a fully tunneled interface for good measure.

Maybe always do the initial update check without pinning to a specific network ID, and then if the actual downloading fails when pinning to a network ID, tell the user that if they use WireGuard in Kernel mode they can try disabling pinning to a specific ID with a warning that it may consume metered network data. Personally I have a beefy data plan so it won't affect me.

**Comment by chenxiaolong** [comment]
Great, thanks for testing! I like your suggestions and have implemented them in #126.

**Comment by nixigaj** [comment]
Looks great!

https://github.com/user-attachments/assets/04d84cb3-f93c-4024-a29c-892fa2572208
